name: Latest blog post workflow

on:
  schedule:
    - cron: '0 * * * *'   # runs hourly
  workflow_dispatch:       # lets you run it manually from the Actions tab

permissions:
  contents: write          # allow the action to commit to the repo

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: 'https://medium.com/feed/@bisbis.kamil'
          max_post_count: 5
